-- create table departments (
-- 	dep_no varchar(10) primary key,
-- 	dept_name varchar(20)
-- );

-- Create table dept_emp (
-- 	emp_no varchar(10),
-- 	dept_no varchar(10),
-- 	from_date date,
-- 	to_from date
-- );

-- Create table dept_managers (
-- 	dept_no varchar(10),
-- 	emp_no varchar(10),
-- 	from_date date,	
-- 	to_date date
-- );

-- create table employees (
-- 	emp_no varchar(10) primary key,
-- 	birth_date date,
-- 	first_name varchar(30),
-- 	last_name varchar(30),
-- 	gender varchar (5),
-- 	hire_date date
-- );
-- create table salaries (
-- 	emp_no varchar(10),
-- 	salary varchar(15),
-- 	from_date date,
-- 	to_date date
-- );
-- create table titles (
-- 	emp_no varchar(10),
-- 	title varchar(30),
-- 	from_date date,
-- 	to_date date
-- );
